# Generated by Django 4.1.2 on 2022-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('description', models.TextField(help_text='Event description', verbose_name='Event description')),
                ('start_time', models.TimeField(help_text='Event starting time', verbose_name='Event starting time')),
                ('end_time', models.TimeField(help_text='Event ending time', verbose_name='Event ending time')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendar',
            },
        ),
    ]
